config/routes.rb
Repositoryhome::Application.routes.draw do
  # Users
  devise_for :users
  resources :users

  # Repositories
  resources :repositories

  # Settings
  get    '/settings',               to:  'settings#index'
  put    '/settings',               to:  'settings#update_user_details'
  get    '/settings/keys/new',      to:  'settings#new_key', as: :new_key
  get    '/settings/keys/:id/edit', to:  'settings#edit_key', as: :edit_key
  post   '/settings/keys',          to:  'settings#create_key', as: :keys
  put    '/settings/keys/:id',      to:  'settings#update_key', as: :key
  delete '/settings/keys/:id',      to:  'settings#destroy_key', as: :key

  root to: 'repositories#index'
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  MAX_NAME_LENGTH = 64
  MAX_DESCRIPTION_LENGTH = 190

  has_many :permissions, dependent: :delete_all,
                         inverse_of: :repository,
                         uniq: true,
                         autosave: true
  has_many :users, through: :permissions
  accepts_nested_attributes_for :permissions
  attr_accessible :name, :description, :permissions_attributes

  validates :name, presence: true,
                   uniqueness: true,
                   format: { with: /^[A-Za-z\d_-]+$/ },
                   length: { maximum: MAX_NAME_LENGTH }
  validates :description, length: { maximum: MAX_DESCRIPTION_LENGTH }

  scope :with_permission, select('repositories.*, permissions.name as permission')

  before_validation :mark_permissions_for_destruction

  def self.search(query)
    query ? where("repositories.name LIKE ?", "%#{query}%") : scoped
  end

  # The repository name on disk - url friendly and with .git extension.
  def name_on_disk
    "#{name}.git"
  end

  # Uses the git name to generate the full repository path.
  def path
    "#{Repositoryhome.config.repositories_dir}/#{name_on_disk}"
  end

  # Checks whether the repository name given is in use.
  def self.name_taken?(name)
    !find_by_name name
  end

  # From the supplied key id and repository name compute whether the desired
  # access type is allowed for the user.
  #
  # Possible access types - :read and :write.
  def self.find_by_name_key_id_and_access_type(repo_name, key_id, access_type)
    unless [:read, :write].include? access_type
      raise ArgumentError, 'access_type must be :read or :write'
    end

    repo = Repository.find_by_name(repo_name.split('.git').first)
    key = Key.find_by_id(key_id)
    return nil unless repo && key

    user = key.user
    return repo if user.admin?

    permission =
      Permission.where(user_id: user.id, repository_id: repo.id).first
    return nil unless permission

    'rwa'.include?(permission.name) ? repo : nil
  end

  protected

  def mark_permissions_for_destruction
    permissions.each do |permission|
      permission.mark_for_destruction if permission.name.blank?
    end
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  respond_to :html

  # GET /repositories
  def index
    @host = request.host
    @user_has_searched = params[:search] ? true : false
    if current_user.admin?
      @repositories = Repository.search(params[:search])
    else
      @repositories =
        current_user.repositories.with_permission.search(params[:search])
    end
    @number_of_repositories = @repositories.length
    respond_with @repositories
  end

  # GET /repositories/1
  def show
    @host = request.host
    @repository = find_repository(params[:id])
    unless current_user.admin?
      @permission = @repository.permissions.find_by_user_id(current_user).name
    end
    respond_with @repository
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
    prepare_permissions

    respond_with @repository
  end

  # GET /repositories/1/edit
  def edit
    @host = request.host
    @repository = find_repository(params[:id])
    authorize_edit!
    prepare_permissions
  end

  # POST /repositories
  def create
    @repository = Repository.new(params[:repository])

    # Add full permission for the current user (if not an admin).
    unless current_user.admin?
      @repository.permissions.build(user_id: current_user.id, name: 'f')
    end

    respond_to do |format|
      if @repository.save
        format.html do
          redirect_to @repository, notice: 'Repository was successfully created.'
        end
      else
        format.html do
          prepare_permissions
          render action: 'new'
        end
      end
    end
  end

  # PUT /repositories/1
  def update
    @repository = find_repository(params[:id])
    authorize_edit!

    respond_to do |format|
      if @repository.update_attributes(params[:repository])
        format.html do
          redirect_to @repository, notice: 'Repository was successfully updated.'
        end
      else
        format.html do
          prepare_permissions
          render action: 'edit'
        end
      end
    end
  end

  # DELETE /repositories/1
  def destroy
    @repository = find_repository(params[:id])
    authorize_edit!

    @repository.destroy
    respond_with @repository
  end

  private

  def find_repository(id)
    current_user.admin? ? Repository.find(id) : current_user.repositories.find(id)
  end

  def prepare_permissions
    # Find out which users already have a permission for this repository.
    user_ids_with_permission = @repository.permissions.map { |p| p.user_id }
    User.non_admins.each do |user|
      unless user_ids_with_permission.include?(user.id)
        @repository.permissions.build(user_id: user.id)
      end
    end
  end

  def authorize_edit!
    authenticate_user!

    if current_user.admin?
      user_has_sufficient_permission = true
    else
      permission =
        current_user.permissions.where(repository_id: @repository).first
      if permission
        user_has_sufficient_permission = permission.name == 'f'
      else
        user_has_sufficient_permission = false
      end
    end

    return if user_has_sufficient_permission

    flash[:alert] =
      'You do not have sufficient permissions to edit this repository.'
    redirect_to @repository
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
  def repository_url(repository)
    "git@#{@host}:#{repository.name_on_disk}"
  end

  def permission_display_name(name)
    case name
    when 'r'
      'Read'
    when 'w'
      'Read/Write'
    when 'f'
      'Full'
    else
      'None'
    end
  end
end

app/views/repositories/_backlink.html.erb
<% unless current_user.admin? %>
<div class="backlink-container">
  <div class="back">
    <%= link_to '&larr; Back to repositories'.html_safe, repositories_path, class: "back-link" %>
  </div>
  <% unless controller.action_name == 'show' %>
  <div class="cancel">
    <%= link_to 'Cancel'.html_safe, repositories_path, class: "cancel-link" %>
  </div>
  <% end %>
</div>
<%= render "shared/separator" %>
<% end %>

app/views/repositories/_form.html.erb
<%= form_for @repository do |f| %>
  <%= render partial: 'shared/form_errors', locals: { resource: @repository, resource_name: "this repository" } %>
  <div class="repository">
    <div class="repository-main-info">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
      <% if @repository.persisted? %>
      <div class="repository-url">
        <input type="text" value="<%= repository_url(@repository) %>" />
      </div>
      <% end %>
      <div class="repository-description">
        <%= f.label :description %><br />
        <%= f.text_area :description, cols: 80, rows: 4 %>
      </div>
    </div>
    <div class="repository-meta">
      <div class="repository-edit-button-container">
      <% if @repository.persisted? %>
        <%= f.submit "Done", class: "done-button" %>
        <%= link_to 'Delete', @repository, confirm: 'Are you sure you want to delete this repository?', method: :delete, class: 'delete-button' %>
      <% else %>
        <%= f.submit "Create Repository", class: "create-repository-button" %>
      <% end %>
      </div>
      <div class="repository-date-created">
      <% if @repository.persisted? %>
        Date created<br />
        <span><%= @repository.created_at.to_s(:month_day_year) %></span>
      <% end %>
      </div>
    </div>
  </div>
  <h3>Permissions</h3>
  <table>
    <tr>
      <th>User</th><th>Permission</th>
    </tr>
    <% if User.non_admins.any? %>
    <%= f.fields_for :permissions do |b| %>
      <% unless b.object.user_id == current_user.id %>
      <tr>
        <% user = User.find(b.object.user_id) %>
        <td class="row-key">
          <% if current_user.admin? %>
            <%= link_to user.email, user_path(user) %>
          <% else %>
            <%= user.email %>
          <% end %>
        </td>
        <td class="row-value">
          <%= b.hidden_field :user_id %>
          <%= b.hidden_field :repository_id %>
          <%= b.select :name,
                       options_for_select([
                       ['None', ''],
                       ['Read', 'r'],
                       ['Read/Write', 'w'],
                       ['Full', 'f']
          ], selected: b.object.name) %>
        </td>
      </tr>
      <% end %>
    <% end %>
    <% else %>
    <tr><td class="table-message" colspan="2">There are no regular users</td></tr>
    <% end %>
  </table>
  <div class="repository-edit-button-container-bottom">
    <%= link_to '&larr; Back to repositories'.html_safe, repositories_path, class: "back-link" %>
    <% if @repository.persisted? %>
      <%= f.submit "Update", class: "done-button" %>
    <% else %>
      <%= f.submit "Create Repository", class: "create-repository-button" %>
    <% end %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<%= render "backlink" %>
<div id="edit-repository-view">
  <h1>Edit repository</h1>
  <%= render 'form' %>
</div>

app/views/repositories/index.html.erb
<section id="repositories-header">
  <%= link_to '+&nbsp;&nbsp;New Repository'.html_safe, new_repository_path, id: "new-repository" %>
  <%= form_tag repositories_path, method: 'get', id: 'repository-search' do %>
  <p>
    <%= text_field_tag :search, params[:search], id: "search-field" %><%= submit_tag "Search", name: nil, id: "search-button" %>
  </p>
  <% end %>
  <p id="repositories-found">
    <% if @user_has_searched %>
      <% if @number_of_repositories > 0 %> 
        Found <span><%= @number_of_repositories %></span>
        <%= @number_of_repositories == 1 ? "repository" : "repositories" %>
      <% else %>
        No repositories found...
      <% end %>
    <% else %>
      There
      <%= @number_of_repositories == 1 ? "is" : "are" %>
      <span><%= @number_of_repositories %></span>
      <%= @number_of_repositories == 1 ? "repository" : "repositories" %>
      available
    <% end %>
  </p>
</section>
<%= render "shared/separator" %>
<% if alert %>
  <div id="alert"><p><%= alert %></p></div>
<% end %>
<div id="repositories">
  <% @repositories.each do |repository| %>
  <div class="repository" id="repository-<%= repository.name %>">
    <div class="repository-main-info">
      <%= link_to repository.name, repository, class: "repository-name" %>
      <div class="repository-users">
        Users <span><%= repository.users.length %></span>
      </div>
      <div class="repository-url">
        <input type="text" value="<%= repository_url(repository) %>" />
      </div>
      <% if repository.description %>
      <div class="repository-description">
        <%= repository.description %>
      </div>
      <% end %>
    </div>
    <div class="repository-meta">
      <div class="repository-edit-button-container">
        <% if current_user.admin? || repository.permission == "f" %>
          <%= link_to 'Edit', edit_repository_path(repository), class: "edit-button" %>
        <% else %>
          <span class="permission-name"><%= permission_display_name(repository.permission) %></span>
        <% end %>
      </div>
      <div class="repository-date-created">
        Date created<br />
        <span><%= repository.created_at.to_s(:month_day_year) %></span>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/repositories/new.html.erb
<%= render "backlink" %>
<div id="edit-repository-view">
  <h1>New repository</h1>
  <%= render 'form' %>
</div>

app/views/repositories/show.html.erb
<%= render "backlink" %>
<% if notice %>
  <div id="notice"><p><%= notice %></p></div>
<% end %>
<% if alert %>
  <div id="alert"><p><%= alert %></p></div>
<% end %>
<div id="single-repository-view">
  <div class="repository">
    <div class="repository-main-info">
      <%= link_to @repository.name, @repository, class: "repository-name" %>
      <div class="repository-url">
        <input type="text" value="<%= repository_url(@repository) %>" />
      </div>
      <% if @repository.description %>
      <div class="repository-description">
        <%= @repository.description %>
      </div>
      <% end %>
    </div>
    <div class="repository-meta">
      <div class="repository-edit-button-container">
        <% if current_user.admin? || @permission == "f" %>
          <%= link_to 'Edit', edit_repository_path(@repository), class: "edit-button" %>
          <%= link_to 'Delete', @repository, confirm: 'Are you sure you want to delete this repository?', method: :delete, class: 'delete-button' %>
        <% else %>
          <span class="permission-name">
            <%= permission_display_name(@permission) %>
          </span>
        <% end %>
      </div>
      <div class="repository-date-created">
        Date created<br />
        <span><%= @repository.created_at.to_s(:month_day_year) %></span>
      </div>
    </div>
  </div>
  <h3>Permissions</h3>
  <table>
    <tr>
      <th>User</th><th>Permission</th>
    </tr>
    <% if User.non_admins.any? %>
    <% @repository.permissions.each do |permission| %>
    <tr>
      <td class="row-key">
        <% if current_user.admin? %>
          <%= link_to find_user_email(permission.user_id), user_path(permission.user_id) %>
        <% else %>
          <%= find_user_email(permission.user_id) %>
        <% end %>
      </td>
      <td><%= permission_display_name(permission.name) %></td>
    </tr>
    <% end %>
    <% else %>
    <tr><td class="table-message" colspan="2">There are no regular users</td></tr>
    <% end %>
  </table>
  <br /><br />
  <%= link_to '&larr; Back to repositories'.html_safe, repositories_path, class: "back-link" %>
</div>