config/routes.rb
Repositoryhome::Application.routes.draw do
  # Users
  devise_for :users
  resources :users

  # Repositories
  resources :repositories

  # Settings
  get    '/settings',               to:  'settings#index'
  put    '/settings',               to:  'settings#update_user_details'
  get    '/settings/keys/new',      to:  'settings#new_key', as: :new_key
  get    '/settings/keys/:id/edit', to:  'settings#edit_key', as: :edit_key
  post   '/settings/keys',          to:  'settings#create_key', as: :keys
  put    '/settings/keys/:id',      to:  'settings#update_key', as: :key
  delete '/settings/keys/:id',      to:  'settings#destroy_key', as: :key

  root to: 'repositories#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  has_many :permissions,
           dependent: :delete_all,
           inverse_of: :user
  has_many :repositories, through: :permissions
  has_many :keys, dependent: :delete_all

  accepts_nested_attributes_for :permissions

  # Setup accessible (or protected) attributes for your model.
  attr_accessible :email,
                  :password,
                  :password_confirmation,
                  :remember_me,
                  :admin,
                  :permissions_attributes

  validates :email, uniqueness: true,
                    length: { within: 5..254 }, # According to http://stackoverflow.com/questions/386294/maximum-length-of-a-valid-email-id/574698#574698
                    format: { with: /^.+@.+$/i }

  # Generate password if no password is set.
  before_validation :generate_password, on: :create, if: "password.blank?"
  before_validation :mark_permissions_for_destruction

  def self.non_admins
    where(admin: false).all
  end

  protected

  def generate_password
    return unless self.password.blank?

    # Generate a 16 character long random alphanumeric password.
    chars = [('a'..'z'), ('A'..'Z'), (0..9)].map { |i| i.to_a }.flatten
    password = (0..16).map { chars[rand(chars.length)] }.join
    self.password = self.password_confirmation = password
  end

  def mark_permissions_for_destruction
    permissions.each do |permission|
      permission.mark_for_destruction if permission.name.blank?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize_admin!
  respond_to :html

  # GET /users
  def index
    @users = User.where("users.id != ?", current_user.id).all
    respond_with @users
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
    respond_with @user
  end

  # GET /users/new
  def new
    @user = User.new
    prepare_permissions

    respond_with @user
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    prepare_permissions
  end

  # POST /users
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html do
          redirect_to @user, notice: 'User was successfully created.'
        end
      else
        format.html do
          prepare_permissions
          render action: 'new'
        end
      end
    end
  end

  # PUT /users/1
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html do
          redirect_to @user, notice: 'User was successfully updated.'
        end
      else
        format.html do
          prepare_permissions
          render action: 'edit'
        end
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with @user
  end

  private

  def prepare_permissions
    # Find out which users already have a permission for this repository.
    repository_ids_with_permission = @user.permissions.map { |p| p.repository_id }
    Repository.all.each do |repository|
      unless repository_ids_with_permission.include?(repository.id)
        @user.permissions.build(repository_id: repository.id)
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render partial: 'shared/form_errors', locals: { resource: @user, resource_name: "this user" } %>
  <div class="user">
    <div class="user-main-info">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>
    <div class="user-meta">
      <div class="user-edit-button-container">
      <% if @user.persisted? %>
        <%= f.submit "Done", class: "done-button" %>
        <%= link_to 'Delete', @user, confirm: 'Are you sure you want to delete this user?', method: :delete, class: 'delete-button' %>
      <% else %>
        <%= f.submit "Create User", class: "create-user-button" %>
      <% end %>
      </div>
      <div class="user-is-admin">
        <%= f.check_box :admin %>&nbsp;Admin
      </div>
    </div>
  </div>
  <% unless @user.admin %>
  <h3>Permissions</h3>
  <table>
    <tr>
      <th>Repository</th><th>Permission</th>
    </tr>
    <%= f.fields_for :permissions do |b| %>
    <tr>
      <% repository = Repository.find(b.object.repository_id) %>
      <td class="row-key">
        <%= link_to repository.name, repository_path(repository) %>
      </td>
      <td class="row-value">
          <%= b.hidden_field :user_id %>
          <%= b.hidden_field :repository_id %>
          <%= b.select :name,
                       options_for_select([
                       ['None', ''],
                       ['Read', 'r'],
                       ['Read/Write', 'w'],
                       ['Full', 'f']
          ], selected: b.object.name) %>
      </td>
    </tr>
    <% end %>
  </table>
  <% end %>
  <div class="user-edit-button-container-bottom">
    <%= link_to '&larr; Back to users'.html_safe, users_path, class: "back-link" %>
    <% if @user.persisted? %>
      <%= f.submit "Done", class: "done-button" %>
    <% else %>
      <%= f.submit "Create User", class: "create-user-button" %>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id="edit-user-view">
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div id="users-header">
  <div id="users-found">
    <% if @users.length > 0 %>
    There
    <%= @users.length == 1 ? "is" : "are" %>
    <span><%= @users.length %></span>
    <%= @users.length == 1 ? "user" : "users" %>
    <% else %>
      There are no other users
    <% end %>
  </div>
  <%= link_to '+&nbsp;&nbsp;New User'.html_safe, new_user_path, id: "new-user" %>
</div>
<%= render "shared/separator" %>
<% if notice %>
  <div id="notice"><p><%= notice %></p></div>
<% end %>
<% if alert %>
  <div id="alert"><p><%= alert %></p></div>
<% end %>

<div id="users">
  <% @users.each do |user| %>
  <div class="user">
    <div class="user-main-info">
      <%= link_to user.email, user, class: "user-email" %>
      <div class="user-repositories">
        <% if user.admin? %>
        All repositories
        <% else %>
          <% count = user.repositories.length %>
          <% if count > 0 %>
            <%= count == 1 ? "Repository" : "Repository".pluralize %>
            <span><%= count %></span>
          <% else %>
            No repositories
          <% end %>
        <% end %>
      </div>
      <div class="user-date-added">
        Date Added
        <span><%= user.created_at.to_s(:month_day_year) %></span>
      </div>
    </div>
    <div class="user-meta">
      <div class="user-edit-button-container">
        <%= link_to 'Edit', edit_user_path(user), class: "edit-button" %>
      </div>
      <% if user.admin? %>
      <div class="user-is-admin">Admin</div>
      <% end %>        
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="edit-user-view">
  <h1>New user</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<% if notice %>
  <div id="notice"><p><%= notice %></p></div>
<% end %>
<% if alert %>
  <div id="alert"><p><%= alert %></p></div>
<% end %>
<div id="single-user-view">
  <div class="user">
    <div class="user-main-info">
      <%= link_to @user.email, @user, class: "user-email" %>
      <div class="user-repositories">
      <% if @user.admin? %>
        All repositories
      <% else %>
        <% count = @user.repositories.length %>
        <% if count > 0 %>
          <%= count == 1 ? "Repository" : "Repository".pluralize %>
          <span><%= count %></span>
        <% else %>
          No repositories
        <% end %>
      <% end %>
      </div>
      <div class="user-date-added">
        Date Added
        <span><%= @user.created_at.to_s(:month_day_year) %></span>
      </div>
    </div>
    <div class="user-meta">
      <div class="user-edit-button-container">
        <%= link_to 'Edit', edit_user_path(@user), class: "edit-button" %>
      </div>
      <% if @user.admin? %>
      <div class="user-is-admin">Admin</div>
      <% end %>        
    </div>
  </div>
  <% unless @user.admin? %>
  <h3>Permissions</h3>
  <% if @user.permissions.length > 0 %>
  <table>
    <tr>
      <th>Repository</th><th>Permission</th>
    </tr>
    <% @user.permissions.each do |permission| %>
    <tr>
      <td class="row-key">
        <%= link_to find_repository_name(permission.repository_id), repository_path(permission.repository_id) %>
      </td>
      <td><%= permission_display_name(permission.name) %></td>
    </tr>
    <% end %>
  </table>
  <% else %>
    <p>This user doesn't have access to any repositories.</p>
  <% end %>
  <% end %>
  <div class="bottom-nav">
    <br /><br />
    <%= link_to '&larr; Back to users'.html_safe, users_path, class: "back-link" %>
  </div>
</div>