config/routes.rb
Repositoryhome::Application.routes.draw do
  # Users
  devise_for :users
  resources :users

  # Repositories
  resources :repositories

  # Settings
  get    '/settings',               to:  'settings#index'
  put    '/settings',               to:  'settings#update_user_details'
  get    '/settings/keys/new',      to:  'settings#new_key', as: :new_key
  get    '/settings/keys/:id/edit', to:  'settings#edit_key', as: :edit_key
  post   '/settings/keys',          to:  'settings#create_key', as: :keys
  put    '/settings/keys/:id',      to:  'settings#update_key', as: :key
  delete '/settings/keys/:id',      to:  'settings#destroy_key', as: :key

  root to: 'repositories#index'
end

app/views/shared/_form_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2 class="error-title">
      Oops! <%= pluralize(resource.errors.count, "error") %>
      prohibited <%= resource_name %> from being saved:
    </h2>
    <ul>
    <% resource.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<nav>
  <%= link_to image_tag("repositoryhome.png", alt: "Repository Home"), root_path, id: "logo" %>
  <div>
    <span><%= current_user.email %></span>
    <span><%= link_to 'Settings', settings_path, id: 'settings-link', class: current_page?(settings_path) ? "active-settings" : "" %></span>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
  </div>
</nav>
<%= admins_only do %>
<div id="admin-background"></div>
<ul id="admin-navigation">
  <li class="tab-label <%= "active-tab" if current_page?(root_path) or current_page?(repositories_path)%>">
    <%= link_to 'Repositories', repositories_path %>
  </li>
  <li class="tab-label <%= "active-tab" if current_page?(users_path) %>">
    <%= link_to 'Users', users_path %>
  </li>
</ul>
<% end %>

app/views/shared/_separator.html.erb
<div class="double-top-border"></div>