config/routes.rb
Repositoryhome::Application.routes.draw do
  # Users
  devise_for :users
  resources :users

  # Repositories
  resources :repositories

  # Settings
  get    '/settings',               to:  'settings#index'
  put    '/settings',               to:  'settings#update_user_details'
  get    '/settings/keys/new',      to:  'settings#new_key', as: :new_key
  get    '/settings/keys/:id/edit', to:  'settings#edit_key', as: :edit_key
  post   '/settings/keys',          to:  'settings#create_key', as: :keys
  put    '/settings/keys/:id',      to:  'settings#update_key', as: :key
  delete '/settings/keys/:id',      to:  'settings#destroy_key', as: :key

  root to: 'repositories#index'
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
    @user = current_user
    @key = Key.new
    @keys = current_user.keys
  end

  def update_user_details
    @user = current_user

    # If either :password or :confirm_password are submitted we go for the
    # full update. Otherwise it's just an email change.
    unless params[:user][:password].empty? && params[:user][:password_confirmation].empty?
      attrs = params[:user]
    else
      attrs = params[:user].except(:password, :password_confirmation)
    end

    respond_to do |format|
      if @user.update_attributes(attrs)
        format.html do
          sign_in @user, bypass: true
          redirect_to settings_url, notice: 'Account details successfully updated.'
        end
      else
        format.html do
          @key = Key.new
          @keys = current_user.keys

          render action: 'index'
        end
      end
    end
  end

  def new_key
    @key = Key.new
    respond_to { |format| format.html }
  end

  def create_key
    @key = Key.new(params[:key])
    @key.user_id = current_user.id

    respond_to do |format|
      if @key.save
        format.html do
          redirect_to settings_url, notice: 'The SSH key was successfully added.'
        end
      else
        format.html do
          @user = current_user
          @keys = current_user.keys

          render action: 'new_key'
        end
      end
    end
  end

  def edit_key
    @key = current_user.keys.find(params[:id])
  end

  def update_key
    @key = current_user.keys.find(params[:id])

    respond_to do |format|
      if @key.update_attributes(params[:key])
        format.html do
          redirect_to settings_url, notice: 'The SSH key was updated.'
        end
      else
        format.html do
          @user = current_user
          @keys = current_user.keys

          render action: 'edit_key'
        end
      end
    end
  end

  def destroy_key
    @key = current_user.keys.find(params[:id])
    @key.destroy
    respond_to do |format|
      format.html { redirect_to settings_url }
    end
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_backlink.html.erb
<% unless current_user.admin? %>
<div class="backlink-container">
  <div class="back">
    <%= link_to '&larr; Back to settings'.html_safe, settings_path, class: "back-link" %>
  </div>
  <% unless controller.action_name == 'show' %>
  <div class="cancel">
    <%= link_to 'Cancel'.html_safe, settings_path, class: "cancel-link" %>
  </div>
  <% end %>
</div>
<%= render "shared/separator" %>
<% end %>

app/views/settings/_key_form.html.erb
<div class="key">
<%= form_for @key do |f| %>
  <%= render partial: 'shared/form_errors', locals: { resource: @key, resource_name: "this key" } %>
  <div class="key-name-and-body">
    <div class="key-name-field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="key-body-field">
      <%= f.label :body %><br />
      <%= f.text_area :body, rows: "7", cols: "60" %>
    </div>
  </div>
  <div class="add-key-button">
    <% if @key.persisted? %>
      <%= f.submit "Done", class: "done-button" %>
      <%= link_to 'Delete', @key, confirm: 'Are you sure you want to delete this key?', method: :delete, class: 'delete-button' %>
    <% else %>
      <%= f.submit "Add Key", id: "create-key-button" %>
    <% end %>
  </div>
<% end %>
</div>

app/views/settings/_user_details_form.html.erb
<%= form_for(@user, url: settings_path, method: :put) do |f| %>
  <%= render partial: 'shared/form_errors', locals: { resource: @user, resource_name: "your account details" } %>
  <div class="update-email-field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="update-password-field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="update-password-confirm-field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="update-user-details-submit">
    <%= f.submit "Update user details", id: "update-user-details-button" %>
  </div>
<% end %>

app/views/settings/edit_key.html.erb
<%= render "backlink" %>
<div id="key-edit-view">
  <h1>Edit Key</h1>
  <%= render 'key_form' %>
  <br /><br />
  <%= link_to '&larr; Back to settings'.html_safe, settings_path, class: "back-link" %>
</div>

app/views/settings/index.html.erb
<div id="settings-view">
  <% if notice %>
    <div id="notice"><p><%= notice %></p></div>
  <% end %>
  <% if alert %>
    <div id="alert"><p><%= alert %></p></div>
  <% end %>
  <h1>Settings</h1>
  <%= render "shared/separator" %>
  <h2>User details</h2>
  <%= render "user_details_form" %>
  <%= render "shared/separator" %>
  <h2 id="keys-section-title">Keys</h2>
  <div id="new-key-button-container">
    <%= link_to 'New Key', new_key_path, id: "new-key-button" %>
  </div>
  <table>
    <tr>
      <th class="key-name">Name</th><th>Body</th><th></th>
    </tr>
    <% if @keys.length > 0 %>
    <% @keys.each do |key| %>
    <tr>
      <td class="key-name"><%= link_to "#{key.name}", edit_key_path(key) %></td>
      <td class="key-body"><%= key.body %></td>
      <td><%= link_to 'Delete', key, confirm: 'Are you sure you want to delete this key?', method: :delete, class: "delete-button" %></td>
    </tr>
    <% end %>
    <% else %>
    <tr>
      <td colspan="2" class="table-message">
        You have to add an SSH key before you can access any repositories
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/settings/new_key.html.erb
<%= render "backlink" %>
<div id="key-edit-view">
  <h1>New Key</h1>
  <%= render 'key_form' %>
  <br /><br />
  <%= link_to '&larr; Back to settings'.html_safe, settings_path, class: 'back-link' %>
</div>